name: Merge & Save
on:
  workflow_dispatch:
  schedule:
    - cron: '55 12 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: GetTime
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_OUTPUT
      - name: Download and Merge Conf Files
        run: |
          #!/bin/bash
          CONF_FILES=(
            "anti-AD|Anti Advertising for smartdns|https://anti-ad.net/anti-ad-for-smartdns.conf"
            "adrules|AdRules SmartDNS List|https://adrules.top/smart-dns.conf"
            "neodevhost|neodevhost SmartDNS List|https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_smartdns.conf"
          )
          MERGED_CONTENT=""
          for CONF in "${CONF_FILES[@]}"; do
            PROJECT=$(echo "$CONF" | cut -d'|' -f1)
            DESCRIPTION=$(echo "$CONF" | cut -d'|' -f2)
            URL=$(echo "$CONF" | cut -d'|' -f3)
            echo "Downloading $PROJECT from $URL"
            CONTENT=$(curl -s "$URL")
            if [ $? -eq 0 ]; then
              MERGED_CONTENT+="# Source: $PROJECT - $DESCRIPTION\n"
              MERGED_CONTENT+="$CONTENT\n\n"
            else
              echo "Failed to download $PROJECT from $URL"
            fi
          done
          echo "$MERGED_CONTENT" > anti-ad-smartdns.conf
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add anti-ad-smartdns.conf
          git commit -am "${{ steps.date.outputs.date }}"
          git push origin master
